# Generated by Django 3.2.8 on 2022-01-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klanten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klant', models.CharField(max_length=200)),
                ('E_mail', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_kind', models.CharField(choices=[('New project', 'New project'), ('Progress', 'Progress'), ('Internal', 'Internal')], default=[1], max_length=200)),
                ('klant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generic_form.klanten')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Questionnaire name')),
                ('question_category', models.CharField(choices=[('Multichoice', 'Multichoice'), ('Choose N', 'Choose N'), ('Text', 'Text'), ('Number', 'Number')], default=None, max_length=200, verbose_name='Question category')),
                ('questionnaire', models.ManyToManyField(to='generic_form.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generic_form.question')),
            ],
        ),
    ]
