# Generated by Django 3.2.8 on 2022-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.CharField(choices=[('Deltaplan', 'Deltaplan'), ('Thuis in het Zeeuwse Verpleeghuis', 'Thuis in het Zeeuwse Verpleeghuis'), ('Uitvoeringsagenda', 'Uitvoeringsagenda'), ('Zeeuwse Zorg Coalitie', 'Zeeuwse Zorg Coalitie'), ('Communicatie/evenementen', 'Communicatie/evenementen')], default=[1], max_length=200),
        ),
    ]
