# Generated by Django 3.2.8 on 2022-01-16 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('VZ', '0002_project_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thema',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Kennis en Inzicht', 'Kennis en Inzicht'), ('Kiezen en Toeleiden', 'Kiezen en Toeleiden'), ('Leren en Opleiden', 'Leren en Opleiden'), ('Werken en Behoud', 'Werken en Behoud')], default=[1], max_length=72),
        ),
    ]
