# Generated by Django 3.2.8 on 2022-01-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VZ', '0004_auto_20220116_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('januari t/m maart 2022', 'januari t/m maart 2022'), ('april t/m Juni 2022', 'april t/m Juni 2022'), ('juli t/m september 2022', 'juli t/m september 2022'), ('oktober t/m december 2022', 'oktober t/m december 2022')], default=[1], max_length=200)),
                ('projectfase', models.CharField(choices=[('Ontwerpfase', 'Ontwerpfase'), ('Realisatiefase', 'Realisatiefase')], default=[1], max_length=200)),
                ('uitgevoerde_activiteit', models.CharField(max_length=500)),
                ('behaalde_doel', models.CharField(max_length=500)),
                ('verwachte_activiteit', models.CharField(max_length=500)),
                ('verwachte_doel', models.CharField(max_length=500)),
                ('leermoment', models.CharField(choices=[('ja', 'ja'), ('nee', 'nee')], default=[1], max_length=200)),
                ('leermoment_toelichting', models.CharField(max_length=500)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VZ.project')),
            ],
        ),
    ]
